apiVersion: v1
kind: Service
metadata:
  name: {{ include "oopapp.fullname" . }}
  labels:
    app: {{ include "oopapp.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "oopapp.name" . }}
