USER-SUPPLIED VALUES:
env:
- name: discovery.type
  value: single-node
esConfig:
  elasticsearch.yml: |-
    xpack.security.enabled: false
    xpack.security.http.ssl.enabled: false
image:
  pullPolicy: IfNotPresent
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.16.1
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
service:
  nodePort: 30920
  port: 9200
  type: NodePort
